### PR TITLE
Retag existing image instead of building image without additional layers

### PR DESCRIPTION
**Pull request by mering**
which is more efficient

### CODE REVIEW

**Review by sethvargo — APPROVED** [review]

**Comment by sethvargo** [comment]
Hi @mering - are you able to sign your commmits?

**Comment by mering** [comment]
@sethvargo I currently don't have the bandwidth to set this up. Feel free to close this PR if it is a requirement.

**Comment by sethvargo** [comment]
Hi @mering - signed commits will be required for any work on Alphabet repositories unfortunately. In the meantime, I'll pull these changes into a different branch and push them up as myself.

**Comment by mering** [comment]
@sethvargo I found out that one can use the SSH key for signing as well.

**Pull request closed without merging**
